name: clean_arch_examples
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter

  chewie: ^1.11.3
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  file_picker: ^10.1.9
  font_awesome_flutter: ^10.8.0
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  http: ^1.4.0
  iconly: ^1.0.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  lottie: ^3.3.1
  open_file: ^3.5.10
  path_provider: ^2.1.5
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  swipe_to: ^1.0.6
  url_launcher: ^6.3.1
  video_thumbnail: ^0.5.6
  youtube_explode_dart: ^2.4.2
  google_fonts: ^6.2.1
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  firebase_ui_auth: ^1.16.1

dev_dependencies:
  bloc_test: ^10.0.0
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.2
  firebase_storage_mocks: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  google_sign_in_mocks: ^0.3.0
  mocktail: ^1.0.4
  very_good_analysis: ^8.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/Google_sans_round_light.ttf
          weight: 300
        - asset: assets/fonts/Google_sans_round_regular.ttf
          weight: 400